/* Generated By:JavaCC: Do not edit this line. AlphaTreeConstants.java Version 5.0 */
public interface AlphaTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASS = 1;
  public int JJTVOID = 2;
  public int JJTIDENTIFIER = 3;
  public int JJTPUBLIC = 4;
  public int JJTTRUE = 5;
  public int JJTFALSE = 6;
  public int JJTTHIS = 7;
  public int JJTINTEGER = 8;
  public int JJTNEW = 9;
  public int JJTLENGTH = 10;
  public int JJTSTATIC = 11;
  public int JJTMAIN = 12;
  public int JJTSTRING = 13;
  public int JJTINT = 14;
  public int JJTBOOLEAN = 15;
  public int JJTEXTENDS = 16;
  public int JJTCLASSBODY = 17;
  public int JJTVAR_DECLARATION = 18;
  public int JJTMAINDECLARATION = 19;
  public int JJTARGS = 20;
  public int JJTARG = 21;
  public int JJTARRAY = 22;
  public int JJTBODY = 23;
  public int JJTMETHOD_DECLARATION = 24;
  public int JJTRETURN = 25;
  public int JJTEQUAL = 26;
  public int JJTINDEX = 27;
  public int JJTIF = 28;
  public int JJTELSE = 29;
  public int JJTCONDITION = 30;
  public int JJTWHILE = 31;
  public int JJTNEWFUNC = 32;
  public int JJTDOT = 33;
  public int JJTAND = 34;
  public int JJTMINOR = 35;
  public int JJTPLUS = 36;
  public int JJTMINUS = 37;
  public int JJTPRODUCT = 38;
  public int JJTDIVISION = 39;
  public int JJTNOT = 40;
  public int JJTFUNC = 41;
  public int JJTFUNC_ARGS = 42;
  public int JJTFUNC_ARG = 43;
  public int JJTERROR_SKIPTO = 44;


  public String[] jjtNodeName = {
    "Program",
    "CLASS",
    "void",
    "IDENTIFIER",
    "PUBLIC",
    "TRUE",
    "FALSE",
    "THIS",
    "INTEGER",
    "NEW",
    "LENGTH",
    "STATIC",
    "MAIN",
    "STRING",
    "INT",
    "BOOLEAN",
    "EXTENDS",
    "ClassBody",
    "VAR_DECLARATION",
    "MainDeclaration",
    "Args",
    "Arg",
    "ARRAY",
    "Body",
    "METHOD_DECLARATION",
    "RETURN",
    "EQUAL",
    "INDEX",
    "If",
    "Else",
    "Condition",
    "While",
    "newFunc",
    "DOT",
    "AND",
    "MINOR",
    "PLUS",
    "MINUS",
    "PRODUCT",
    "DIVISION",
    "NOT",
    "FUNC",
    "FUNC_ARGS",
    "FUNC_ARG",
    "error_skipto",
  };
}
/* JavaCC - OriginalChecksum=5fb3b3a1720c1f64dd0cb1ad3651761a (do not edit this line) */
