/* Generated By:JJTree&JavaCC: Do not edit this line. AlphaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AlphaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPEN_CURLY_BRACKET = 6;
  /** RegularExpression Id. */
  int CLOSE_CURLY_BRACKET = 7;
  /** RegularExpression Id. */
  int OPEN_PARENTHESIS = 8;
  /** RegularExpression Id. */
  int CLOSE_PARENTHESIS = 9;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 10;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 11;
  /** RegularExpression Id. */
  int INT = 12;
  /** RegularExpression Id. */
  int BOOLEAN = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int TRUE = 16;
  /** RegularExpression Id. */
  int THIS = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int FALSE = 19;
  /** RegularExpression Id. */
  int EQUAL = 20;
  /** RegularExpression Id. */
  int COMMA = 21;
  /** RegularExpression Id. */
  int NEW = 22;
  /** RegularExpression Id. */
  int LENGTH = 23;
  /** RegularExpression Id. */
  int AND = 24;
  /** RegularExpression Id. */
  int MINOR = 25;
  /** RegularExpression Id. */
  int PLUS = 26;
  /** RegularExpression Id. */
  int MINUS = 27;
  /** RegularExpression Id. */
  int PRODUCT = 28;
  /** RegularExpression Id. */
  int DIVISON = 29;
  /** RegularExpression Id. */
  int DOT = 30;
  /** RegularExpression Id. */
  int CLASS = 31;
  /** RegularExpression Id. */
  int EXTENDS = 32;
  /** RegularExpression Id. */
  int PUBLIC = 33;
  /** RegularExpression Id. */
  int STATIC = 34;
  /** RegularExpression Id. */
  int VOID = 35;
  /** RegularExpression Id. */
  int MAIN = 36;
  /** RegularExpression Id. */
  int EXCLAMATION_POINT = 37;
  /** RegularExpression Id. */
  int NORMAL_COMMA = 38;
  /** RegularExpression Id. */
  int RETURN = 39;
  /** RegularExpression Id. */
  int STRING = 40;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 41;
  /** RegularExpression Id. */
  int IDENTIFIER = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"int\"",
    "\"boolean\"",
    "\"if\"",
    "\"else\"",
    "\"true\"",
    "\"this\"",
    "\"while\"",
    "\"false\"",
    "\"=\"",
    "\";\"",
    "\"new\"",
    "\"length\"",
    "\"&&\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\".\"",
    "\"class\"",
    "\"extends\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"!\"",
    "\",\"",
    "\"return\"",
    "\"String\"",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
  };

}
